# Generated by Django 4.2.30 on 2026-07-09 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTTSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Netflix', 'Netflix'), ('Spotify', 'Spotify'), ('YouTube Premium', 'YouTube Premium'), ('Prime Video', 'Amazon Prime Video'), ('Disney+', 'Disney+'), ('HBO Max', 'Max / HBO Max'), ('Other', 'Other Service')], max_length=30)),
                ('plan_name', models.CharField(help_text='e.g. Premium Ultra HD, Family Plan', max_length=100)),
                ('total_slots', models.PositiveIntegerField(help_text='Total number of members allowed in the group (excluding owner)')),
                ('price_per_slot', models.DecimalField(decimal_places=2, help_text='Price in USD or local currency per slot', max_digits=8)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('One-time', 'One-time')], default='Monthly', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Describe expectations, payment terms, etc.')),
                ('status', models.CharField(choices=[('Active', 'Active (Slots Available)'), ('Full', 'Full (No Slots)'), ('Closed', 'Closed')], default='Active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ott_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTTMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved / Joined'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ott.ottsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ott_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subscription', 'user')},
            },
        ),
    ]
