# Generated by Django 4.2.30 on 2026-07-09 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Books', 'Books & Study Material'), ('Electronics', 'Electronics & Gadgets'), ('Bicycles', 'Bicycles & Transport'), ('Lab Equipment', 'Lab Equipment & Tools'), ('Furniture', 'Furniture & Decor'), ('Essentials', 'Other Essentials')], max_length=30)),
                ('listing_type', models.CharField(choices=[('Sell', 'For Sale'), ('Rent', 'For Rent'), ('Exchange', 'For Exchange'), ('Share', 'Free / Share')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if Exchange or Share', max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('New', 'Brand New'), ('Like New', 'Like New / Mint'), ('Good', 'Good / Gently Used'), ('Fair', 'Fair / Shows Wear'), ('Poor', 'Poor / Heavy Wear')], max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('image_url', models.URLField(blank=True, help_text='Optional external image URL for demo seeding', null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Rented', 'Rented'), ('Inactive', 'Inactive')], default='Available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='marketplace.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
